### ISSUE TITLE
no setup.py in local fairseq directory

### ISSUE THREAD

**Issue by tonytan48** [sacmehta/delight#2]
Hi,

 Thank you for your interesting work. I was trying to reproduce some of the translation task and learn the model better. But it seems there is no setup.pt in fairseq and I cannot install fairseq from this source.

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/qingyu.tan/projects/delight/fairseq
(base) 

Should I copy an setup.py from fairseq or do you have a modified version of setup.py?

**Comment by tonytan48** [comment]
I tried to copy the setup.py and the README.md for the local fairseq setup.
But the following error occured:

    ERROR: Command errored out with exit status 1:
     command: /home/qingyu.tan/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/qingyu.tan/projects/delight/fairseq/setup.py'"'"'; __file__='"'"'/home/qingyu.tan/projects/delight/fairseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/qingyu.tan/projects/delight/fairseq/
    Complete output (14 lines):
    running develop
    running egg_info
    writing fairseq.egg-info/PKG-INFO
    writing dependency_links to fairseq.egg-info/dependency_links.txt
    writing entry points to fairseq.egg-info/entry_points.txt
    writing requirements to fairseq.egg-info/requires.txt
    writing top-level names to fairseq.egg-info/top_level.txt
    reading manifest file 'fairseq.egg-info/SOURCES.txt'
    writing manifest file 'fairseq.egg-info/SOURCES.txt'
    running build_ext
    cythoning fairseq/data/data_utils_fast.pyx to fairseq/data/data_utils_fast.cpp
    creating fairseq
    creating fairseq/data
    error: /home/qingyu.tan/projects/delight/fairseq/fairseq/data/data_utils_fast.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/qingyu.tan/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/qingyu.tan/projects/delight/fairseq/setup.py'"'"'; __file__='"'"'/home/qingyu.tan/projects/delight/fairseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by sacmehta** [comment]
setup.py file exists in the folder.

https://github.com/sacmehta/delight/blob/653477389c492e48bf165ae7bf0f073674a7fc89/setup.py#L1


You need to be inside delight folder to install it

**Comment by annahung31** [comment]
Maybe you can update your [README](https://github.com/sacmehta/delight/tree/1197d8ffbcff5c3bfc3b6a040a2ae8af811278c4#requirements-and-installation) since it said `cd fairseq` which might be confused to us.

**Comment by sacmehta** [comment]
That’s a good catch. I copy pasted installation instructions from Fairseq.

Thanks for pointing it. I have updated the README file.
