### ISSUE TITLE
Unable to do fp16 training.

### ISSUE THREAD

**Issue by Raghava14** [sacmehta/delight#4]
It is mentioned to install [apex](https://github.com/sacmehta/delight/blob/master/README.md#requirements-and-installation) but in the training [command](https://github.com/sacmehta/delight/blob/master/nmt_wmt14_en2de.py#L35) no option has been given. Tried to use default `--fp16` command from fairseq but getting the below error.
```
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUB
LAS_GEMM_DFALT_TENSOR_OP)` 
```
Want to do to train on `--fp16` . Please suggest. Thanks.

**Comment by sacmehta** [comment]
There is a bug in cuDNN/CUDA version that it can't handle large batch size for matrix multiplication.

Which CUDA version are you using?

**Comment by Raghava14** [comment]
I am using CUDA version `10.1 ` . But my other trainings with `transformer_big` are running with` fp16` from fairseq in the same version do you think it is related to it ?

**Comment by sacmehta** [comment]
You need to use CUDA 10.2+. Since Transformer_big uses NVIDIA's dedicated kernel, it does not encounter matrix multiplication issue when using large matrices.

There was a bug in CUDA 10.1. See here:  https://github.com/pytorch/pytorch/issues/24018#issuecomment-528004576

**Comment by Raghava14** [comment]
Thanks will check out closing for now.
